name: ✨ Feat
description: 새로운 기능을 추가할 때 사용합니다.
title: "[Feat] <제목>"
labels: ["⚙️ feature"]
body:
- type: textarea
  attributes:
    label: description
    description: description
    placeholder: description
  validations:
    required: false
